# Generated by Django 2.0.1 on 2018-01-16 10:47

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GolferProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('about_my_golf', models.TextField(blank=True, default='', null=True)),
                ('biggest_golfing_achievement', models.CharField(max_length=255, null=True)),
                ('current_handicap', models.IntegerField(default=18)),
                ('lowest_handicap', models.IntegerField(default=18)),
                ('golf_club', models.CharField(max_length=255)),
                ('whats_in_your_bag', models.TextField(blank=True, default='', max_length=600, null=True)),
                ('swing', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
