# Generated by Django 2.0.1 on 2018-01-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0003_auto_20180111_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='golferprofile',
            name='about_my_golf',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
