# Generated by Django 2.0.1 on 2018-02-01 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0009_auto_20180201_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golferprofile',
            name='golfer',
            field=models.OneToOneField(blank=True, default='accounts.User_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
