# Generated by Django 2.0.1 on 2018-01-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='brand_description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='product_long_description',
        ),
        migrations.AddField(
            model_name='equipment',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(default='', max_length=35),
        ),
    ]
