# Generated by Django 2.0.1 on 2018-02-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipmentgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentgallery',
            name='countries',
        ),
        migrations.DeleteModel(
            name='EquipmentGallery',
        ),
    ]
