# Generated by Django 2.0.1 on 2018-01-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20180112_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='contact_email',
            field=models.CharField(default='', max_length=80),
        ),
    ]
