# Generated by Django 2.0.1 on 2018-01-26 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20180118_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='name',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='image',
            new_name='item_image',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='price',
            new_name='item_price',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='location',
            new_name='your_location',
        ),
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(blank=True, default='user.username', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
