# Generated by Django 2.0.1 on 2018-01-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20180126_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='published_date',
        ),
    ]
