# Generated by Django 2.0.1 on 2018-02-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20180130_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='item',
            new_name='item_name',
        ),
    ]
