# Generated by Django 2.0.1 on 2018-02-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20180216_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='condition',
        ),
        migrations.AddField(
            model_name='ad',
            name='your_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='ad',
            name='item_name',
            field=models.CharField(default='', max_length=45),
        ),
    ]
