# Generated by Django 2.0.1 on 2018-01-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contact_number',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(default=''),
        ),
    ]
