# Generated by Django 2.0.1 on 2018-01-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationblogpost',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
